baseURL: /
languageCode: en-us
title: Sławomir Liszniański
keywords: Vans RV-10 aviation build
copyright: 'Slawomir Lisznianski &#60;sl@aggati.com&#62;'
theme: hello-ng
params:
  homeSubtitle: Irregular chronicles of a curious person.
  portraitpath: /img/me.jpg
  portrait:
    path: /static/img/me.jpg
    alt: Sławomir Liszniański
menu:
  main:
    - identifier: aviator
      name: Aviator
      url: /blog/aviator

    - identifier: cook
      name: Cook
      url: /blog/cook