baseURL: /
languageCode: en-us
title: Sławomir Liszniański
theme: hello-ng
params:
  homeSubtitle: personal journal
  portraitpath: /img/me.jpg
  portrait:
    path: /static/img/me.jpg
    alt: Sławomir Liszniański
menu:
  main:
    - identifier: aviator
      name: Aviator
      url: /blog/aviator

    - identifier: cook
      name: Cook
      url: /blog/cook

#   - identifier: ea-build
#     name: EA build
#     url: /blog/ea-build
#
#   - identifier: hacking
#     name: Hacking
#     url: /blog/hacking
#
#   - identifier: fashia
#     name: Fashia
#     url: /blog/fashia
