baseURL = "/"
languageCode = "en-us"
title = "Sławomir Liszniański"
theme = "hugo"

[params]
	homeSubtitle = "Aviator \u25cf Coder \u25cf Fashia \u25cf Pizzaiolo"
	portraitpath = "/img/me.jpg"

[params.portrait]
	path = "/static/img/me.jpg"
	alt = "Slawomir"

[[menu.main]]
		identifier = "rv10"
		name       = "RV-10"
		url        = "/blog/rv10"
